language: python
python:
  - "3.8"
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install --dev codecov
script:
  - make ci-test
  - codecov
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)