language: python
python:
  - "3.8"
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install --dev codecov
script:
  - scrapy check
  - coverage run --source='.' -m unittest discover --verbose
  - codecov